name: "MSTeams notification action"
description: "Action to notify ms teams about workflow status"
author: "METRO Digital GmbH"
inputs:
  webhook_url:
    description: "teams incoming webhook url"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
