name: "MSTeams notification action"
description: "Action to notify ms teams about workflow status"
author: "METRO Digital GmbH"
inputs:
  webhook_url:
    description: "teams incoming webhook url"
    required: true
  workflow_run_success:
    description: "notify on workflow run success"
    required: false
    default: 'true'
  workflow_run_failure:
    description: "notify on workflow run success"
    required: false
    default: 'true'
runs:
  using: "node20"
  main: "dist/index.js"
