name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
          npm run format-check
          npm run lint
          npm run build
          npm run integrity
  notify: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Send pull requests to Microsoft Teams
        uses: ./
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
